name: kuickmeat_vendor_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  image_picker: ^0.7.4
  provider: ^5.0.0
  location: ^4.1.1
  geocoder: ^0.2.1
  email_validator: ^2.0.1
  flutter_slider_drawer: ^2.0.0
  flutter_easyloading: ^3.0.0
  chips_choice: ^2.0.1
  geolocator: ^7.1.0
  url_launcher: ^6.0.6
  map_launcher: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:

  uses-material-design: true


  assets:
   - images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf